### ISSUE TITLE
请问有计划支持sonarr v4吗

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/Sonarr-Title-i18n#1]
如题

**Comment by LuckyPuppy514** [comment]
当前 v4 只有开发版，小问题较多，暂不打算支持
而且 v4 UI 应该会像 Radarr 那样支持多语言，所以到时候这个项目可能就没必要了

**Comment by PN62323424** [comment]
好吧，不过sonarr 的多语言版本我感觉都好几年了都没出炉

**Comment by sumingyd** [comment]
> 当前 v4 只有开发版，小问题较多，暂不打算支持 而且 v4 UI 应该会像 Radarr 那样支持多语言，所以到时候这个项目可能就没必要了

没用的，V4依然需要你这个。
已经在discord上问过开发者，
TVDB的数据目前只采集英文。而且开发者只使用TVDB，也并不会增加TMDB的支持。
虽然UI是多语言，但同样的列表依然只是列表。。数据依然来自于TVDB。

如果你这个东西再改改，把sonarr的自动重命名，剧集文件夹的名称和单集文件的名称让他支持中文就更好了。
我现在苦于找不到sonarr的替代品。事实上，界面和功能都是sonarr这样的。提供商使用的TMDB就完美了。

**Comment by sumingyd** [comment]
TVDB简直难用的要死。。API难用。。。WEB网页更难用

**Comment by sumingyd** [comment]
刚没仔细看，原来是个油猴脚本，要是替换他个文件来支持这些就好了
